### ISSUE TITLE
Another nginx exporter

### ISSUE THREAD

**Issue by hellower** [prometheus/docs#1330] opened 2019-04-10 06:26 UTC
Third-party exporters 
https://prometheus.io/docs/instrumenting/exporters/

Another Nginx exporter  ==>
https://github.com/nginxinc/nginx-prometheus-exporter

documentation needs to be updated.

**Comment by brian-brazil** [comment] 2019-04-10 09:40
Dupe of #1318

**Closed by brian-brazil** 2019-04-10 09:40 UTC
